### ISSUE TITLE
[BUG] poetry 1.1.8 breaks installs

### ISSUE THREAD

**Issue by dpemmerich** [coreemu/core#596]
**Describe the bug**
Trying to install coreemu from source using the the install.sh script on a fresh Ubuntu install fails when trying to install core-daemon. This is due to pipx installing version 1.1.8 of poetry which has a bug with the most up-to-date Ubuntu. The poetry bug can be found at:
https://github.com/python-poetry/poetry/issues/4416

**To Reproduce**
install ubuntu 20.04
update - 
```sudo apt update && sudo apt upgrade```
install pip
```
sudo apt install python3-pip
python3 -m pip install -U pip
git clone https://github.com/coreemu/core.git
cd core
./install.sh -l
```
Error:
```
setup to install CORE using apt
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
The following NEW packages will be installed:
  python3-venv python3.8-venv
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,684 B of archives.
After this operation, 38.9 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04 [5,456 B]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 python3-venv amd64 3.8.2-0ubuntu2 [1,228 B]
Fetched 6,684 B in 0s (64.2 kB/s)
Selecting previously unselected package python3.8-venv.
(Reading database ... 77589 files and directories currently installed.)
Preparing to unpack .../python3.8-venv_3.8.10-0ubuntu1~20.04_amd64.deb ...
Unpacking python3.8-venv (3.8.10-0ubuntu1~20.04) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../python3-venv_3.8.2-0ubuntu2_amd64.deb ...
Unpacking python3-venv (3.8.2-0ubuntu2) ...
Setting up python3.8-venv (3.8.10-0ubuntu1~20.04) ...
Setting up python3-venv (3.8.2-0ubuntu2) ...
Processing triggers for man-db (2.9.1-1) ...
Collecting pipx
  Downloading pipx-0.16.4-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.5 MB/s
Collecting packaging>=20.0
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 8.0 MB/s
Collecting userpath>=1.6.0
  Downloading userpath-1.7.0-py2.py3-none-any.whl (14 kB)
Collecting argcomplete<2.0,>=1.9.4
  Downloading argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 8.9 MB/s
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from userpath>=1.6.0->pipx) (7.0)
Installing collected packages: pyparsing, userpath, packaging, argcomplete, pipx
Successfully installed argcomplete-1.12.3 packaging-21.0 pipx-0.16.4 pyparsing-2.4.7 userpath-1.7.0
/home/user/.local/bin is already in PATH.

⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
  installed package invoke 1.6.0, Python 3.8.10
  These apps are now globally available
    - inv
    - invoke
done! ✨ 🌟 ✨
installing core locally: True
installing core with prefix: /usr/local
checking for old installations ... done
installing system dependencies ... done
installing system grpcio-tools ... done
building core ... done
installing vcmd/gui ... done
installing core ... \Encountered a bad command exit code!

Command: 'cd daemon && poetry build -f wheel'

Exit code: 1

Stdout:

  at /usr/lib/python3.8/subprocess.py:1704 in _execute_child
      1700│                     else:
      1701│                         err_filename = orig_executable
      1702│                     if errno_num != 0:
      1703│                         err_msg = os.strerror(errno_num)
    → 1704│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1705│                 raise child_exception_type(err_msg)
      1706│
      1707│
      1708│         def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,

Stderr:
```

**Expected behavior**
I expect that the install should complete without issue. 

**Screenshots**
See error above

**Desktop (please complete the following information):**
 - OS: 18.04 and 20.04
 - CORE Version 7.5.1
 - EMANE Version [e.g. 1.2.4]

**Additional context**
This seems to be a breaking bug since pretty much any new install on ubuntu will currently fail

**Comment by dpemmerich** [comment]
this can be remediated by updating line 213 in tasks.py to specify the poetry version to 1.1.7
    ```c.run("pipx install poetry", hide=hide)```
to:
  ```  c.run("pipx install poetry==1.1.7", hide=hide)```

**Comment by dpemmerich** [comment]
updated title because based on the poetry bug report, it appears it's broken on more than just ubuntu

**Comment by PatrickTague** [comment]
same issue here.  the suggestion to fix via line 213 edit in tasks.py didn't work for me.

**Comment by PatrickTague** [comment]
i was able to make it work by running the `pipx install poetry==1.1.7` command on its own at the command line outside of the install script, then adding `--force` to the relevant command on line 213, which i think just makes that command irrelevant... :/

**Comment by PatrickTague** [comment]
i take it back. that worked once, but not in a fresh 20.04 vm...

**Comment by PengfeiM** [comment]
same issue here，and the solution doesn't work for me

**Comment by PengfeiM** [comment]
but it seems a little different in my isuue
here are the picture![255e987e321e9d88.png](https://user-images.githubusercontent.com/45191163/132346095-b399a098-97ca-447a-8a5b-31e88789f6c7.png)

**Comment by PengfeiM** [comment]
> but it seems a little different in my isuue
> here are the picture![255e987e321e9d88.png](https://user-images.githubusercontent.com/45191163/132346095-b399a098-97ca-447a-8a5b-31e88789f6c7.png)

it worked！！！！！！！
Thx so much。

**Comment by PatrickTague** [comment]
any hint to get this to work reliably? i fought this bug for several hours yesterday, and i need to get this working for students in my class

**Comment by bharnden** [comment]
I'll take a look today, I had noted a slightly different issue related to this, to lock in versions for both pipx and poetry to help avoid update issues like this from cropping up.

I'll be testing 20.4.3 LTS. Potentially the line edit noted in #597 is sufficient for now.

**Comment by dpemmerich** [comment]
@PatrickTague  : unsure. I've been able to repeatedly install from a fresh ubuntu 20.04.3 install following:

```
sudo apt install python3-pip
python3 -m pip install -U pip
git clone https://github.com/coreemu/core.git
cd core
# edit tasks.py line 213 to set poetry==1.1.7
sed -i 's/pipx install poetry/pipx install poetry==1.1.7/' tasks.py. #<<- taken from comments in Issue #598
./install.sh -l
```

I do see it looks like you're using invoke to do the install. I just tested that too, and was able to consistently complete the install multiple times using:
```
sudo apt update && sudo apt -y upgrade
sudo apt -y install python3-pip python3-venv
python3 -m pip install -U pip
git clone https://github.com/coreemu/core.git
cd core
#edit line 213 in tasks.py where pipx installs poetry
sed -i 's/pipx install poetry/pipx install poetry==1.1.7/' tasks.py
## line 213 should read as     c.run("pipx install poetry==1.1.7", hide=hide)
python3 -m pip install -U pipx
python3 -m pipx ensurepath
export PATH=$PATH:~/.local/bin
pipx install invoke
invoke install
```

note: my pipx version that installed automatically in the last test I ran is:
```
pipx --version
0.16.4
```

**Comment by PatrickTague** [comment]
running your script word-for-word in a fresh 20.04.3 LTS vm:
```
installing core virtual environment ... \Encountered a bad command exit code!

Command: 'cd daemon && poetry install --no-dev'

Exit code: 1

Stdout:

      512│             if isinstance(e.reason, _SSLError):
      513│                 # This branch is for urllib3 v1.22 and later.
      514│                 raise SSLError(e, request=request)
      515│ 
    → 516│             raise ConnectionError(e, request=request)
      517│ 
      518│         except ClosedPoolError as e:
      519│             raise ConnectionError(e, request=request)
      520│ 


Stderr:
```

**Comment by PatrickTague** [comment]
second try worked (after uninstalling a few things via pipx).  not sure if there's a dependency loop or what, but the second time's the charm, apparently...unless i'm speaking too soon again.

**Comment by TinCanTech** [comment]
Editing `tasks.py` Is **not** sufficient.

Deleting `/home/$user/.local` **and** editing `tasks.py` fixed it.
```
tct@ub20:~/core$ ./install.sh -l
setup to install CORE using apt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (20.1.1-2).
python3-venv is already the newest version (3.8.6-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libffi7 libicu66 libjson-c4 linux-headers-5.4.0-42 linux-headers-5.4.0-42-generic linux-image-5.4.0-42-generic linux-modules-5.4.0-42-generic
  linux-modules-extra-5.4.0-42-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Collecting pipx
  Using cached pipx-0.16.4-py3-none-any.whl (53 kB)
Collecting userpath>=1.6.0
  Using cached userpath-1.7.0-py2.py3-none-any.whl (14 kB)
Collecting argcomplete<2.0,>=1.9.4
  Using cached argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting packaging>=20.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from userpath>=1.6.0->pipx) (7.1.2)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: userpath, argcomplete, pyparsing, packaging, pipx
Successfully installed argcomplete-1.12.3 packaging-21.0 pipx-0.16.4 pyparsing-2.4.7 userpath-1.7.0
/home/tct/.local/bin is already in PATH.

⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
  installed package invoke 1.6.0, Python 3.8.10
  These apps are now globally available
    - inv
    - invoke
done! ✨ 🌟 ✨
installing core locally: True
installing core with prefix: /usr/local
checking for old installations ... done
installing system dependencies ... done
installing system grpcio-tools ... done
building core ... done
installing vcmd/gui ... done
installing core ... Processing ./dist/core-7.5.1-py3-none-any.whl
Collecting pillow==7.1.2
  Downloading Pillow-7.1.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
Collecting invoke==1.4.1
  Downloading invoke-1.4.1-py3-none-any.whl (210 kB)
Collecting netaddr==0.7.19
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6 MB)
Collecting protobuf==3.12.2
  Downloading protobuf-3.12.2-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
Collecting pyproj==2.6.1.post1
  Downloading pyproj-2.6.1.post1-cp38-cp38-manylinux2010_x86_64.whl (10.9 MB)
Collecting fabric==2.5.0
  Downloading fabric-2.5.0-py2.py3-none-any.whl (51 kB)
Requirement already satisfied: pyyaml==5.3.1 in /usr/lib/python3/dist-packages (from core==7.5.1) (5.3.1)
Collecting mako==1.1.3
  Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
Collecting lxml==4.5.1
  Downloading lxml-4.5.1-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
Collecting grpcio==1.27.2
  Downloading grpcio-1.27.2-cp38-cp38-manylinux2010_x86_64.whl (2.7 MB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf==3.12.2->core==7.5.1) (49.3.1)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf==3.12.2->core==7.5.1) (1.15.0)
Collecting paramiko>=2.4
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib/python3/dist-packages (from mako==1.1.3->core==7.5.1) (1.1.1)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko>=2.4->fabric==2.5.0->core==7.5.1) (3.0)
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko>=2.4->fabric==2.5.0->core==7.5.1) (1.4.0)
Collecting cffi>=1.1
  Downloading cffi-1.14.6-cp38-cp38-manylinux1_x86_64.whl (411 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pillow, invoke, netaddr, protobuf, pyproj, pycparser, cffi, bcrypt, paramiko, fabric, mako, lxml, grpcio, core
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.2.0
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
Successfully installed bcrypt-3.2.0 cffi-1.14.6 core-7.5.1 fabric-2.5.0 grpcio-1.27.2 invoke-1.4.1 lxml-4.5.1 mako-1.1.3 netaddr-0.7.19 paramiko-2.7.2 pillow-7.1.2 protobuf-3.12.2 pycparser-2.20 pyproj-2.6.1.post1
done
installing scripts and /etc/core ... done
installing systemd service ... done
installing ospf mdr ... done

install complete!
tct@ub20:~/core$ git diff
diff --git a/tasks.py b/tasks.py
index bdebffc1..3d756c3a 100644
--- a/tasks.py
+++ b/tasks.py
@@ -210,7 +210,7 @@ def install_core(c: Context, hide: bool) -> None:
 
 
 def install_poetry(c: Context, dev: bool, local: bool, hide: bool) -> None:
-    c.run("pipx install poetry", hide=hide)
+    c.run("pipx install poetry==1.1.7", hide=hide)
     if local:
         with c.cd(DAEMON_DIR):
             c.run("poetry build -f wheel", hide=hide)

```
Thanks

**Comment by bharnden** [comment]
@TinCanTech likely due to not starting from a fresh install, as you were in the middle of the failure.

**Comment by antonymrtn** [comment]
Hello ! I had the same issue as described, but after replacing the line 213, I have a new error :
<img width="754" alt="Capture d’écran 2021-09-20 à 07 30 44" src="https://user-images.githubusercontent.com/59775893/133960434-7c6c4b19-0a3a-4ce1-a2f5-be043ad321cd.png">

**Comment by bharnden** [comment]
@antonymrtn this would need to be from a fresh attempt, not in the middle of a failed attempt.

**Comment by bharnden** [comment]
latest release should fix this

**Comment by antonymrtn** [comment]
I still have a problem. I uninstall core, I try again, and now I have a problem with "installing core virtual environment", and more particularly with the command "poetry install --no-dev".
<img width="771" alt="Capture d’écran 2021-09-22 à 22 52 06" src="https://user-images.githubusercontent.com/59775893/134420146-5a02888a-6842-44e9-80b3-8fb552d960ac.png">

I install core with your last release, but it still won't work. I don't understand why...

**Comment by bharnden** [comment]
Are you trying this on an already failed machine? I would try all over from scratch.

**Comment by antonymrtn** [comment]
I just make a new Virtual Machine, and it still doesn't work.

**Comment by bharnden** [comment]
You are saying the above screenshot is what you see now, with a brand new VM? What exact VM are you using? version and desktop/server?

**Comment by bharnden** [comment]
For reference I just now pulled the latest release on a fresh VM Ubuntu Desktop 20.04.3, which is the LTS and everything went as expected.

Using the following to install:
`./install.sh`

**Comment by antonymrtn** [comment]
My VM is an ubuntu-20.04.3 server. And I have exactly the same issue with the brand new VM.

And I use `./install.sh` to install core. But it won't work.

**Comment by antonymrtn** [comment]
Also not sure if this has an impact, but the host machine is a Mac M1, which requires me to use an ARM version of ubuntu. Could the problem come from there?

**Comment by bharnden** [comment]
I would start with trying the desktop version as a start to eliminate possibilities, but it may very well be related to the ARM factor. I don't have a local environment to test that out.

I imagine, that is likely a unique property of your setup than the others here, but maybe not.

**Comment by PatrickTague** [comment]
this issue persists in a fresh Ubuntu 21.04 VM.  it still flags the same line `cd daemon && poetry install --no-dev` as hitting an error

**Comment by PatrickTague** [comment]
same issue in a fresh Ubuntu 21.10 VM:

```
installing core virtual environment ... -Encountered a bad command exit code!

Command: 'cd daemon && poetry install --no-dev'

Exit code: 1

Stdout:

      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│ 
      1103│         return decode(output)
      1104│ 
      1105│     def execute(self, bin, *args, **kwargs):

```

**Comment by bharnden** [comment]
I would try the LTS and not the latest, as a start.
